[features]
seeds = false
skip-lint = false
[programs.devnet]
childmasterpda = "4KHdwrNqmC7gMeeGpWYKdxyjScArBnmP2wsgg8cAY1aJ"
master = "2oQLML5jy1ydfaXAJAHoqr661yeumX6U4N3ESrDg1vdJ"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/air/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
